services:
  python:
    build:
      context: .
      dockerfile: python.dockerfile
    volumes:
      - ./src/python:/usr/src/app
      - ./datasets:/usr/datasets
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]